services:
  clients_db:
    container_name: db_clients_data
    hostname: db_clients_data
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: "db_clients_data"
    ports:
      - 5432:5432
    networks:
      - rate_limiting
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go_rate_limiter
    restart: always
    depends_on:
      - clients_db
    environment:
      DB_HOST: localhost
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: admin
      DB_NAME: db_clients_data
    ports:
      - "8080:8080"
    networks:
      - rate_limiting

networks:
  rate_limiting:
    driver: bridge